language: r
sudo: required
r_packages:
- knitr
r_github_packages:
- jimhester/covr
- eddelbuettel/drat
after_failure:
  email:
    recipients:
    - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash drat.sh
env:
  global:
    secure: Um6EVGXORtTyE3rk6+NY79rTXhk5ZVXBbL8R26nJ/oHg0H6jSgrJUzvlHXq0sndTLInc66kkmpfQ05fjkpcrTcKKxaojcZ7dp0MXdHTf9HTMjFq4WSS0xYUKRxSLD5s8zdIUCqxo4Jg+Ehy9sIVdLbPW1nfg/bXMxVLrci+KMwE=
