language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
r_packages:
- covr
- drat
r_github_packages:
- cloudyr/travisci
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
- Rscript -e "travisci::restart_last_build('cloudyr/awspack')"
env:
  global:
    secure: KHyK5zgFySQJAqAplG+e53/7l50pjbu4e6t3fWryCxH5pYBgZWLcGmHPTZkxusfzi12vVwvwu2gFwscP6JrMfoTYUMhL/CWPMjhS6Q7XvSq6538+3E/edS5sN4ZKhG2vq7jjD+EwSn36o2AzlW/YePfPQIT4smxyKIE3CzFSbus=
