language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_failure:
  email:
    recipients:
    - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: KHyK5zgFySQJAqAplG+e53/7l50pjbu4e6t3fWryCxH5pYBgZWLcGmHPTZkxusfzi12vVwvwu2gFwscP6JrMfoTYUMhL/CWPMjhS6Q7XvSq6538+3E/edS5sN4ZKhG2vq7jjD+EwSn36o2AzlW/YePfPQIT4smxyKIE3CzFSbus=
